### PR TITLE
Removed dependency on nette/nette.

### PR DESCRIPTION
**Pull request by FilipStryk**

### CODE REVIEW

**Comment by davidkudera** [comment]
Oh cool :+1: 

I'm just thinking if it woudn't be better to require `^2.2` instead of `^2.3`. There can be people using this version

**Comment by FilipStryk** [comment]
You're right, I'll change it.

**Comment by davidkudera** [comment]
Thanks, and can you now also squash all commits together please?

**Comment by FilipStryk** [comment]
Yes, I can.

**Comment by davidkudera** [comment]
cool, thank you :beers:

**Pull request merged**
