### PR TITLE
Fixed Nette 3.0 compatibility

### PR DESCRIPTION
**Pull request by vojta001**
I was just too impatient to wait for @Daaarkling to comply with his PR #35 with your requirements so I implemented the changes you @davidkudera requested. All credits go to him but since this is under MIT...

### CODE REVIEW

**Comment by Daaarkling** [comment]
@davidkudera sorry I have kind a different priorities now, but I'm glad someone finally did it :-)

**Comment by davidkudera** [comment]
@Daaarkling If you're apologizing for having different priorities, I would have too since I'm not event using nette anymore :wink:

@vojta001 thank you for your work :beers:

**Comment by vojta001** [comment]
Could you please create a tag (release) to allow us to benefit from this fix (possibly after merging #39)?

**Comment by davidkudera** [comment]
@vojta001 done

**Comment by foxycode** [comment]
@davidkudera Maybe problem with packagist, but Composer can't find version `2.2.0` and `dev-master` have `nette/di ^2.4` requirement.

**Comment by vojta001** [comment]
@foxycode Hmmmm, interesting. I can now reproduce what you describe. I initially didn't notice since I am for some reason using this in my `composer.json`
```json
"repositories": [
{
    "type": "git",
    "url": "https://github.com/Carrooi/Nette-Menu"
 }
]
```

**Comment by davidkudera** [comment]
It should work now. I moved to GitLab and so I didn't know about the removal of GitHub services.

**Comment by vojta001** [comment]
It works now even without the `repositories` part :+1:

**Pull request merged**
